server:
  port: 8081

spring:
  profiles:
      active: local
  application:
    name: response-lens-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000

  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173}

gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: ${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent}