spring:
  datasource:
    url: jdbc:postgresql://ep-blue-lab-aocz4f6c-pooler.c-2.ap-southeast-1.aws.neon.tech/responselens?sslmode=require
    username: neondb_owner
    password: npg_urAnVQNB0do6

app:
  jwt:
    secret: responselens_super_secure_jwt_secret_key_for_2026_production_at_least_64_chars_long_and_random

gemini:
  api:
    key: AIzaSyBct6eZAXgVofxXIm7B_ZmDP8lrIO6IkNE